INSERT INTO COLOUR (COLOUR_NAME) VALUES ('Yellow');
INSERT INTO COLOUR (COLOUR_NAME) VALUES ('Blue');
INSERT INTO COLOUR (COLOUR_NAME) VALUES ('Red');

INSERT INTO MAP (PATH, NAME) VALUES ('/map1.jpg', 'Small Preston');
INSERT INTO MAP (PATH, NAME) VALUES ('/map2.jpg', 'Medium Preston');
INSERT INTO MAP (PATH, NAME) VALUES ('/map3.jpg', 'Large Preston');

INSERT INTO GAME (TURN, MAP_ID) VALUES ('1', 1);

INSERT INTO GRAPH_NODE (NUMBER, PIXEL_X, PIXEL_Y, MAP_ID) VALUES('1', '100', '100', '1');
INSERT INTO GRAPH_NODE (NUMBER, PIXEL_X, PIXEL_Y, MAP_ID) VALUES('2', '200', '200', '1');
INSERT INTO GRAPH_NODE (NUMBER, PIXEL_X, PIXEL_Y, MAP_ID) VALUES('3', '300', '300', '1');
INSERT INTO GRAPH_NODE (NUMBER, PIXEL_X, PIXEL_Y, MAP_ID) VALUES('4', '400', '400', '1');

INSERT INTO PLAYER (NICKNAME, IS_MR_X, CURRENT_NODE, GAME_ID, TURN_ORDER) VALUES('Sam',     '1', '1', '1', '0');
INSERT INTO PLAYER (NICKNAME, IS_MR_X, CURRENT_NODE, GAME_ID, TURN_ORDER) VALUES('Ollie',   '0', '2', '1', '1');
INSERT INTO PLAYER (NICKNAME, IS_MR_X, CURRENT_NODE, GAME_ID, TURN_ORDER) VALUES('Nick',    '0', '3', '1', '2');
INSERT INTO PLAYER (NICKNAME, IS_MR_X, CURRENT_NODE, GAME_ID, TURN_ORDER) VALUES('Lesley',  '0', '4', '1', '3');

INSERT INTO EDGE (MAP_ID, GRAPH_NODE_A, GRAPH_NODE_B, COLOUR_ID) VALUES('1', '1', '2', '1');
INSERT INTO EDGE (MAP_ID, GRAPH_NODE_A, GRAPH_NODE_B, COLOUR_ID) VALUES('1', '1', '2', '2');
